# Change these first
owner: Lwnlcks # Your GitHub organization or username, where this repository lives
repo: namgall-status # The name of this repository

sites:
  - name: namuwiki-gall
    url: https://gall.dcinside.com/mgallery/board/lists?id=namuwiki
  - name: namgall-wiki
    url: https://namgall.wikiing.in/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /namgall-status
  logoUrl: https://namgall.wikiing.in/image/24d2ee257bfb9f5831cd9ec60c0ffc16968cd86ea8d62c35cb07f51d.svg
  name: 남갤위키 상태 체크 페이지
  introTitle: "남갤과 남갤위키의 서버 상태를 확인할 수 있는 페이지입니다."
  introMessage: 
  navbar:
    - title: 남갤
      href: https://gall.dcinside.com/mgallery/board/lists?id=namuwiki
    - title: 남갤위키
      href: https://namgall.wikiing.in/
      
i18n:
  footer: 본 페이지는 남갤위키에서 운영하며 [Upptime](https://upptime.js.org)로 구동합니다.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
